DefactoSoftware/LearningSpaces-Landing

source/javascripts/landing.js, source/localizable/_header.erb, source/stylesheets/_header.scss
Addressing issue https://github.com/DefactoSoftware/LearningSpaces-Landing/issues/3.
This is an attempt for the language selection option in the menu. It works but not sure if this is the best way/position to go for.
@dkhgh @romkebon ?
=> [WIP] language selector in menu

locales/de.yml, locales/en.yml, locales/nl.yml, source/layouts/layout.erb, source/layouts/panel.erb, source/localizable/index.html.erb, source/localizable/login/index.html.erb, source/localizable/trial/index.html.erb
Ok, we'll mildaskl out this time ;)
=> [ready] Add description, keywords, change titles

locales/de.yml, locales/en.yml, locales/nl.yml, source/javascripts/sign-in.js, source/localizable/login/index.html.erb, source/stylesheets/_login.scss, source/stylesheets/_sign-in.scss
Depends on https://github.com/DefactoSoftware/LearningSpaces/pull/834
=> check if domains exist before redirecting

source/javascripts/landing.js, source/localizable/_intro.erb, source/localizable/_social.erb, source/stylesheets/_features.scss, source/stylesheets/_social.scss
...crawling the web at night. Alone.
=> [ready] This one is for all the crawlers out there

locales/de.yml, locales/en.yml, locales/nl.yml, source/localizable/_intro.erb
please merge after https://github.com/DefactoSoftware/LearningSpaces/pull/999
=> [ready] redirect trial request to the trial sign up

locales/de.yml, locales/en.yml, locales/nl.yml, source/localizable/_footer.html.erb, source/stylesheets/_footer.scss
Because who knows and it looks pro.
So this is the proposal:
Less text, less clutter.
=> [ready] Add jobs to footer

source/localizable/okc.nl.html.erb, source/localizable/zelfsturende-teams.nl.html.erb
=> [ready] redirect to the trial signup page for all pages

source/localizable/seminar/index.nl.html.erb, source/stylesheets/landing.scss, source/stylesheets/sub/_seminar.scss
http://www.learningspaces.nl/seminar/ (already deployed)
=> [READY] seminar landingpage

locales/de.yml, locales/en.yml, locales/nl.yml, source/localizable/_pricing.erb, source/localizable/trial.html.erb
=> removed the only redirection to /trial instead of sign up

locales/de.yml, locales/en.yml, locales/nl.yml, source/layouts/layout.erb, source/localizable/_pricing.erb, source/stylesheets/_pricing.scss
=> [ready] Pricing

source/layouts/layout.erb, source/localizable/_google_analytics.erb
=> [READY] add GA to new landing

source/javascripts/login.js, source/localizable/_header.erb, source/localizable/login.html.erb, source/stylesheets/components/_base.scss, source/stylesheets/components/_login.scss
Doesn't look great yet, but it should get you going:
=> Port over login page

locales/nl.yml
=> [READY] some minor NL text edits

Gemfile, Gemfile.lock, source/localizable/tour.html.erb, source/robots.txt.erb, source/sitemap.xml.builder
To **exclude pages** from the sitemap.xml and disallow in robots.txt, use `noindex: true` in the page frontmatter:
```frontmatter
---
noindex: true
---
```
=> [READY] Add sitemap.xml and robots.txt

locales/en.yml, locales/nl.yml, source/localizable/404.html.erb
not that pretty, but better than nothing :+1:
=> add custom 404 page

config.rb, locales/en.yml, locales/nl.yml, source/_og_tags.erb, source/layouts/layout.erb, source/localizable/index.html.erb, source/localizable/pricing.html.erb, source/localizable/small-teams.html.erb
Fixes https://github.com/DefactoSoftware/LearningSpaces-Landing/issues/61
=> [READY] Translate title and description meta tags with fallback

locales/en.yml, locales/nl.yml
Fixes https://github.com/DefactoSoftware/LearningSpaces-Landing/issues/59
@dkhgh please review :eyes:
=> [READY] More translations

config.rb, deploy, locales/de.yml, locales/en.yml, locales/nl.yml, source/localizable/_slideshow.erb, source/localizable/_text_large_teams.de.md.erb, source/localizable/_text_large_teams.en.md.erb, source/localizable/_text_large_teams.nl.md.erb, source/localizable/_text_small_teams.de.md.erb, source/localizable/_text_small_teams.en.md.erb, source/localizable/_text_small_teams.nl.md.erb, source/localizable/_text_trainers_educators.de.md.erb, source/localizable/_text_trainers_educators.en.md.erb, source/localizable/_text_trainers_educators.nl.md.erb, source/localizable/faq.html.erb, source/localizable/index.html.erb, source/localizable/large-teams-and-organizations.html.erb, source/localizable/pricing.html.erb, source/localizable/small-teams.html.erb, source/localizable/tour.html.erb, source/localizable/trainers-and-educators.html.erb
=> [READY] Translate webite to German

locales/de.yml
Fixing https://github.com/DefactoSoftware/LearningSpaces-Landing/issues/69
=> [READY] Missing German translations on login page

source/layouts/layout.erb, source/stylesheets/components/_footer.scss, source/stylesheets/components/_header.scss, source/stylesheets/site.css.scss
Fixing https://github.com/DefactoSoftware/LearningSpaces-Landing/issues/55
Chrome (win/mac) :+1:
Firefox (win/mac) :+1:
Safari (mac) :+1:
IE11 :+1:
IE10 :+1:
<= IE9 :-1:
=> [READY] Sticky footer

source/stylesheets/base/_grid-settings.scss, source/stylesheets/components/_header.scss
=> [READY] Fix mobile navigation breakpoint

source/localizable/tour.html.erb, source/stylesheets/components/_anchor.scss, source/stylesheets/components/_base.scss, source/stylesheets/components/_faq.scss
=> [READY] Anchors on tour page

locales/de.yml, locales/en.yml, locales/nl.yml, source/localizable/pricing.html.erb, source/localizable/tour.html.erb, source/stylesheets/_tour.scss, source/stylesheets/base/_variables.scss, source/stylesheets/components/_footer.scss, source/stylesheets/components/_hero.scss, source/stylesheets/components/_pricing.scss, source/stylesheets/components/_quotes.scss, source/stylesheets/site.css.scss
=> [READY] Nicer Pricing page

locales/de.yml, locales/en.yml, locales/nl.yml
**This PR can be merged when [LearningSpaces Payments](https://github.com/DefactoSoftware/LearningSpaces/pull/1479) is live.**
=> [WIP] Payment method FAQ

source/localizable/index.html.erb
> Handleidingen. Werkwijzen. Tips en trucs. In LearningSpaces kan je hele team specialismen met elkaar delen.
=> [READY] NL Landing home meta description

locales/nl.yml, source/localizable/pricing.html.erb
=> [READY] Pricing page 

source/localizable/_contact.erb
=> [ready] remove steef from the team

source/javascripts/faq.js, source/localizable/_faq.erb, source/stylesheets/components/_faq.scss
And collapse by default when JS is enabled.
=>  [READY] Expand all FAQ answers by default

locales/de.yml, locales/en.yml, locales/nl.yml, source/localizable/_faq.erb, source/stylesheets/site.css.scss
**This can be merged once we deploy https://github.com/DefactoSoftware/LearningSpaces/pull/1673**
@DefactoSoftware/learningspaces your opinions on these texts please ❓
=> [READY] Update FAQ

locales/en.yml, locales/nl.yml
Update the Tour page, I'm open to suggestions.
You can compare with the [old (current) content](http://www.learningspaces.io/tour/).
* Updated **Your own Learning Community**
* Updated **Collaborate with your Team**
* Added **Challenge your team**
* Added **Ask your Team**
* Added **Everywhere and Anytime**
* Updated **Excellent and Instant Support**
=> [READY] Update Tour

source/javascripts/vimeo.js, source/layouts/layout.erb, source/localizable/_video.erb
Needs testing and maybe we need to seperate the home from the tour video.
=> [READY] add tracking for vimeo videos

locales/en.yml, locales/nl.yml, source/localizable/_for_who.erb, source/localizable/index.html.erb, source/stylesheets/site.css.scss
=> [READY] bring back the for whom partial

locales/en.yml, locales/nl.yml, source/localizable/index.html.erb
=> [READY] update hero title and quote

locales/nl.yml
=> [READY] replace hebben testimonial with van eijl testimonial

locales/de.yml, locales/en.yml, locales/nl.yml, source/localizable/_video.erb
=> [READY] add german LS video

locales/nl.yml
Let's write the productname always as **LearningSpaces**! :-)
=> [READY] remove space from douma testimonial

locales/nl.yml
Replaced English animation with Dutch
=> [READY] Replace animation

locales/nl.yml
=> Fix typo in Dutch copy

config.rb, source/localizable/_header.erb, source/stylesheets/components/_header.scss
This adds the same styling as hover when the page is active.
=> Add active nav state to header menu

locales/de.yml, locales/en.yml, locales/nl.yml, source/localizable/_text_small_teams.de.md.erb, source/localizable/_text_small_teams.en.md.erb, source/localizable/_text_small_teams.nl.md.erb, source/localizable/pricing.html.erb
By request from Rob the Sales guy, this PR removes all mentions of the freemium till 10 users model.
=> Remove freemium from all copy
